import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./providers/Provider";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Provider>
        <body
          className={`${inter.className} bg-gray-800  text-white`}>
          <Navbar />
          <main
            className="lg:p-20 md:p-10 p-5  space-y-6 "
          >
            {children}

          </main>
        </body>
      </Provider>
    </html>
  );
}
