import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./providers/Provider";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  {
    name: 'Words',
    href: '/'
  },
  {
    name: 'Books',
    href: '/books'
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-screen  text-white bg-gray-800"
    >


      <Provider>
        <body
          className={inter.className}>
          <nav className="bg-gray-700 text-white">
            <ul className="flex">

              {links.map(link => {
                return (
                  <Link
                    href={link.href}
                  >
                    <li
                      key={link.href}

                      className="p-5 hover:bg-gray-600 "
                    >

                      {link.name}
                    </li>
                  </Link>
                )
              })}
            </ul>
          </nav>
          <main
          // className="lg:p-20 p-10 space-y-6"
          >
            {children}

          </main>
        </body>
      </Provider>
    </html>
  );
}
